### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by johnhringiv** [ryanjgallagher/shifterator#18]
Hello Ryan,

I may use this repo for some plots in an upcoming paper. How would you like to be cited?

**Comment by ryanjgallagher** [comment]
Hey there,

There isn't really a good way to cite it right now. We're working on a preprint and hoping it'll be up around end of July / August (fingers crossed.

If you use sentiment shifts, you can cite one of the [early Hedonometer papers](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026752). If you use a JSD shift, you could reference the [Google Books paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0137041) and/or my [BLM paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0195644).

I'll update when there's a preprint.

**Comment by ryanjgallagher** [comment]
Finally have a citation for this! Here's the paper: https://arxiv.org/abs/2008.02250
