### ISSUE TITLE
Modifying System Names

### ISSUE THREAD

**Issue by cvanoort** [ryanjgallagher/shifterator#19]
There are some system name labels that are not correctly updated when the `system_names` kwarg is used for `JSDivergenceShift.get_shift_graph`. I haven't dug into things enough to figure out where those labels get set, but it shouldn't be too hard to fix. As far as I know, the `JSDivergenceShift` is the only shift with this issue.

Example Code:
```python
import random
from itertools import product

from shifterator import JSDivergenceShift

chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
system_1 = {
    c[0] + c[1]: int(random.expovariate(1 / 100)) + 1
    for c in product(chars, repeat=2)
    if random.random() > 0.05
}
system_2 = {
    c[0] + c[1]: int(random.expovariate(1 / 100)) + 1
    for c in product(chars, repeat=2)
    if random.random() > 0.05
}

JSDivergenceShift(system_1, system_2).get_shift_graph(system_names=["A", "B"])
```

Example figure:
![test](https://user-images.githubusercontent.com/9307838/86990436-8fb63a80-c16a-11ea-9276-0de25e237e51.png)

**Comment by ryanjgallagher** [comment]
Closed by #17
