### ISSUE TITLE
How can I load those two example dataset?

### ISSUE THREAD

**Issue by keyuchen21** [ryanjgallagher/shifterator#27]
How can I load those two example datasets?
In the tutorial, there is no mention like to to load those two example datasets

![image](https://user-images.githubusercontent.com/54015474/139686805-2ce5d21c-b483-4eaf-88ca-154409236d68.png)

**Comment by ryanjgallagher** [comment]
Hi there,

The data and code for loading the presidential speeches specifically isn't provided. They're just used as a visual example to show you the functionality of shifterator and how it works with different parameters.

For your own data, you'll just want two dictionaries, where keys are the words and values are their frequencies. So something like:

```
type2freq = {
    'hi': 4,
    'the': 100,
    'happy': 30
}
```

And so on. Let me know if there are any other questions.

**Comment by andyreagan** [comment]
The example code [here](https://github.com/andyreagan/shifterator-case-study-moby-dick) should run, if that helps as another example.
