### ISSUE TITLE
multiple shift

### ISSUE THREAD

**Issue by keyuchen21** [ryanjgallagher/shifterator#31]
is that possible to do multiple shift? 
For example I have a dataset of 2010 - 2022.
Is there anyway I can check the word shift from 2010 to 2022 year by year?

**Comment by ryanjgallagher** [comment]
I'm not sure if I quite follow what you're looking to do. If you have some reference text, and you want to compare the text from each year from 2010 to 2022, you can make a Shift object for each year and compute the word shift graph one-by-one. There's no way to compare multiple texts at the same time. 

If you need to stitch together different graphs, the `get_shift_graph` function returns a Matplotlib `ax` that you should be able to use.

**Comment by keyuchen21** [comment]
thanks! that's very helpful!!!!!
