### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by keyuchen21** [ryanjgallagher/shifterator#32]
'labMT_English' works fine while 'NRC-emotion_anger_Nepali' return errors.

Could you help me with this?

![image](https://user-images.githubusercontent.com/54015474/148281410-1d1cd040-cabc-4a4b-a23f-2caa7c178c69.png)

**Comment by ryanjgallagher** [comment]
Hey there, sorry that it took so long to get back to you on this.

Are your texts in English or Nepali? I believe the error that you're seeing could only happen if none of the words in the sentiment dictionary appear in your texts. If you were trying to measure the sentiment of English text using the Nepali dictionary (or vice veresa), then this is the kind of error you'd get. 

If you want to measure sentiment using the Nepali dictionary and your text isn't already in Nepali, then you'll need to translate it before using Shifterator.
