### ISSUE TITLE
r version

### ISSUE THREAD

**Issue by jwijffels** [ryanjgallagher/shifterator#4]
Interesting visualisation. Why don't you make an R version and add it to this r package https://github.com/bnosac/textplot

**Comment by LizMcQuillan** [comment]
@ryanjgallagher - I would be up for helping out with an R version if you're interested. I think shifterator could easily be a standalone package.

**Comment by ryanjgallagher** [comment]
Yeah, that would be great if you're interested in taking a shot at it! I am not proficient at programming in R, so I won't be able to do it myself any time soon.

**Comment by LizMcQuillan** [comment]
@ryanjgallagher I'm solidly ok with R - used to work in R daily, now just once in a while. Like most people, I suddenly find myself with fewer activities to do these days and all my summer travel plans cancelled so I'll take a stab at it. Might email you for some clarification about your functions when I get started.

**Comment by ryanjgallagher** [comment]
Great, we'd be really excited if you were able to port it to R!

Here's an introduction to the sentiment word shifts: 
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026752

These two papers have descriptions of the JSD word shifts
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0137041
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0195644

The detailed word shifts in the package are based on some work we haven't published yet. If you want to reach out via email I can send you a draft that has all those details written out for the different shifts.

**Comment by LizMcQuillan** [comment]
@ryanjgallagher thanks so much!
