### ISSUE TITLE
Incorrect docstring for JSDivergenceShift

### ISSUE THREAD

**Issue by jspobst** [ryanjgallagher/shifterator#5]
I just pip installed and got version 0.1.2 

The `JSDivergenceShift` class in `symmetric_shift.py` has a bad doc string. It has parameters that are not accepted by the __init__ (eg, type2score_1, type2score_2, and reference_value), and it's missing arguments that _are_ accepted (eg, base, weight_1, weight_2, alpha)

**Comment by ryanjgallagher** [comment]
Thanks for catching this!
